title: "Emre Batu Atakan Personal Website"
description: >
  Emre Batu Atakan - Personal Website

# baseurl: "/my-github-pages-site" # Replace with your repo name
url: "https://EmreBatuAtakan.github.io"

markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - makefile
  - README.md
  - .gitignore