title: "Emre Batu Atakan Personal Website"
description: >
  Emre Batu Atakan - Personal Website

# baseurl: "/my-github-pages-site" # Replace with your repo name
url: "https://EmreBatuAtakan.github.io"

markdown: kramdown
theme: minima

social:
  github: "https://github.com/EmreBatuAtakan"
  linkedin: "https://www.linkedin.com/in/emre-batu-atakan-937887244/"

exclude:
  - Gemfile
  - Gemfile.lock
  - makefile
  - README.md
  - .gitignore